CXF-7264 JPA change userSubject pk to id
Change primary key of UserSubject from login attribute
to id attribute.

Needed because a userSubject instance is per-authentication
and an end-user can be authenticated multiple
times simultaneously (either using different flows or
by multiple end-user using same credentials).

This commit also fixes CXF-7286: PersistenceException on refreshAccessToken
PersistenceException: org.hibernate.HibernateException:
Found shared references to a collection:
org.apache.cxf.rs.security.oauth2.tokens.bearer.BearerAccessToken.audiences